# run grafana
# run elastic search
# add dummy data to elastic search

version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
    ports:
      - "9200:9200"      
    volumes:
      - es_data:/usr/share/elasticsearch/data
    # mem_limit: 1024m
    cpus: 0.5
  elasticsearch-head:
    image: mobz/elasticsearch-head:5-alpine
    ports:
      - "9100:9100"

  grafana:
    image: grafana/grafana:7.3.1
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change this password
    ports:
      - "3000:3000"
    depends_on:
      - elasticsearch
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards  # Custom dashboards directory
    mem_limit: 128m      
    cpus: 0.25
volumes:
  es_data:
  grafana_data:
